# Generated by Django 5.2.7 on 2025-12-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated_at"
            ),
        ),
    ]
