# Generated by Django 5.2.7 on 2025-12-13 20:03

import core.validators
import django.db.models.deletion
import feedback.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='feedbacks',
                related_query_name='feedback',
                to='feedback.feedbackuserprofile',
                verbose_name='author',
            ),
        ),
        migrations.AlterField(
            model_name='feedbackfile',
            name='feedback',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='files',
                related_query_name='file',
                to='feedback.feedback',
                verbose_name='feedback',
            ),
        ),
        migrations.AlterField(
            model_name='feedbackfile',
            name='file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=feedback.models.FeedbackFile.file_path,
                validators=[core.validators.FileSizeValidator(16777216)],
                verbose_name='feedback_file',
            ),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='feedback',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='status_logs',
                related_query_name='status_log',
                to='feedback.feedback',
                verbose_name='feedback',
            ),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='feedback_status_logs',
                related_query_name='feedback_status_log',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
