# Generated by Django 5.2.7 on 2026-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_author_alter_feedbackfile_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(
                choices=[
                    ('received', 'received'),
                    ('pending', 'pending'),
                    ('answered', 'answered'),
                ],
                default='received',
                help_text='Status_help_text',
                max_length=11,
                verbose_name='feedback_status',
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(
                help_text='Feedback_text_help_text', verbose_name='feedback_text'
            ),
        ),
        migrations.AlterField(
            model_name='feedbackuserprofile',
            name='mail',
            field=models.EmailField(
                help_text='Email_help_text', max_length=254, verbose_name='email'
            ),
        ),
        migrations.AlterField(
            model_name='feedbackuserprofile',
            name='name',
            field=models.CharField(
                blank=True,
                help_text='Maximum characters — 150',
                max_length=150,
                null=True,
                verbose_name='name',
            ),
        ),
    ]
