# Generated by Django 5.2.7 on 2025-12-17 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        help_text="Is_the_text_AI_generated",
                        verbose_name="is_ai_generated",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "easy"),
                            ("medium", "medium"),
                            ("hard", "hard"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="difficulty",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation_why_text_is_AI_or_human",
                        verbose_name="explanation",
                    ),
                ),
            ],
            options={
                "verbose_name": "training_text",
                "verbose_name_plural": "training_texts",
                "ordering": ["difficulty", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserTrainingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "training_score",
                    models.IntegerField(
                        default=0,
                        help_text="Current_training_score",
                        verbose_name="training_score",
                    ),
                ),
                (
                    "last_fail_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp_of_last_failed_attempt",
                        null=True,
                        verbose_name="last_fail_timestamp",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_texts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="completed_by_users",
                        to="training.trainingtext",
                        verbose_name="completed_texts",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user_training_progress",
                "verbose_name_plural": "user_training_progresses",
            },
        ),
    ]
