# Generated by Django 5.2.7 on 2025-12-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "training",
            "0002_trainingtext_created_at_trainingtext_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingtext",
            name="is_ai_generated",
            field=models.BooleanField(
                help_text="Is_the_text_AI_generated_question",
                verbose_name="is_ai_generated",
            ),
        ),
    ]
