# Generated by Django 5.2.7 on 2025-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0004_alter_customuser_email_squashed_0005_alter_customuser_avatar",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("customer", "customer"), ("performer", "performer")],
                default="customer",
                max_length=9,
            ),
        ),
    ]
