# Generated by Django 5.2.7 on 2025-12-03 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="texttask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "text_task",
                "verbose_name_plural": "text_tasks",
            },
        ),
        migrations.AlterField(
            model_name="texttask",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="text_tasks",
                related_query_name="text_task",
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="texttask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="created_at"
            ),
        ),
        migrations.AlterField(
            model_name="texttask",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated_at"
            ),
        ),
    ]
