# Generated by Django 5.2.7 on 2025-12-06 19:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tasks",
            "0002_alter_texttask_options_alter_texttask_client_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="ai_score",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="comment"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_at"
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_checks",
                        related_query_name="task_check",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performer",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        related_query_name="check",
                        to="tasks.texttask",
                        verbose_name="task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task_check",
                "verbose_name_plural": "task_checks",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "performer"),
                        name="unique_task_performer",
                    )
                ],
            },
        ),
    ]
