# Generated by Django 5.2.7 on 2025-12-06 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tasks",
            "0002_alter_texttask_options_alter_texttask_client_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="texttask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "text task",
                "verbose_name_plural": "text tasks",
            },
        ),
        migrations.AddField(
            model_name="texttask",
            name="ai_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="texttask",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="text_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="texttask",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="texttask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="texttask",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="texttask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="TaskCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_score", models.FloatField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="expert",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="tasks.texttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "task check",
                "verbose_name_plural": "task checks",
                "ordering": ["-created_at"],
            },
        ),
    ]
