# Generated by Django 5.2.7 on 2025-12-11 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_rename_taskcheck_texttaskcheck_texttask_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="texttaskcheck",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "text_task_check",
                "verbose_name_plural": "text_task_checks",
            },
        ),
        migrations.AlterField(
            model_name="texttaskcheck",
            name="performer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="text_task_checks",
                related_query_name="text_task_check",
                to=settings.AUTH_USER_MODEL,
                verbose_name="performer",
            ),
        ),
    ]
