# Generated by Django 5.2.7 on 2025-12-11 19:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_rename_taskcheck_texttaskcheck_texttask_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="texttaskcheck",
            name="annotated_content",
            field=models.TextField(
                blank=True, verbose_name="annotated_content"
            ),
        ),
        migrations.AlterField(
            model_name="texttask",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="content"
            ),
        ),
    ]
