# Generated by Django 5.2.7 on 2025-12-11 21:14

import core.validators
import django.core.validators
import django.db.models.deletion
import sorl.thumbnail.fields
import tasks.models.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_texttaskcheck_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        upload_to=tasks.models.image.ImageTask.image_path,
                        validators=[
                            core.validators.FileSizeValidator(52428800)
                        ],
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "image_task",
                "verbose_name_plural": "image_tasks",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageTaskCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="ai_score",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="comment"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("published", "published"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "image_task_check",
                "verbose_name_plural": "image_task_checks",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="texttaskcheck",
            name="unique_task_performer",
        ),
        migrations.AddConstraint(
            model_name="texttaskcheck",
            constraint=models.UniqueConstraint(
                fields=("task", "performer"),
                name="unique_texttaskcheck_performer",
            ),
        ),
        migrations.AddField(
            model_name="imagetask",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image_tasks",
                related_query_name="image_task",
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="imagetaskcheck",
            name="performer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image_task_checks",
                related_query_name="image_task_check",
                to=settings.AUTH_USER_MODEL,
                verbose_name="performer",
            ),
        ),
        migrations.AddField(
            model_name="imagetaskcheck",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checks",
                related_query_name="check",
                to="tasks.imagetask",
                verbose_name="task",
            ),
        ),
        migrations.AddConstraint(
            model_name="imagetaskcheck",
            constraint=models.UniqueConstraint(
                fields=("task", "performer"),
                name="unique_imagetaskcheck_performer",
            ),
        ),
    ]
